stages:
  - install
  - test
  - build
  - deploy

image: node:latest

install-job:
  stage: install
  script:
    - npm install
  artifacts:
    paths:
      - ./node_modules

test-job:
  stage: test
  script:
    - echo "Running lint"
    - npm run eslint
    - echo "Running tests"
    - npm run test
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage/clover.xml
    paths:
      - ./coverage

build-job:
  stage: build
  script:
    - echo "building..."
    - npm run build
  artifacts:
    paths:
      - ./build

deploy-job:
  stage: deploy
  script:
    - echo "deploying..."
  only:
    - sandbox
    - master
