stages:
  - install
  - test
  - build
  - deploy

image: node:latest

install-job:
  stage: install
  script:
    - npm install

test-job:
  stage: test
  script:
    - echo "Running lint"
    - npm run eslint
    - echo "Running tests"
    - npm run test

build-job:
  stage: build
  script:
    - echo "building..."
    - npm run build

deploy-job:
  stage: deploy
  script:
    - echo "deploying..."
