stages:
  - install
  - test
  - build
  - deploy

image: node:latest

cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - .npm/

install-job:
  stage: install
  script:
    - npm ci --cache .npm --prefer-offline
  artifacts:
    paths:
      - ./node_modules

lint-job:
  stage: test
  script:
    - echo "Running lint"
    - npm run eslint

test-job:
  stage: test
  script:
    - echo "Running tests"
    - npm run test
  artifacts:
    paths:
      - ./coverage

build-job:
  stage: build
  script:
    - echo "building..."
    - npm run build
  artifacts:
    paths:
      - ./build
  only:
    - sandbox
    - master

deploy-job:
  stage: deploy
  script:
    - echo "deploying..."
  only:
    - sandbox
    - master
